name: ci
on: [ push, pull_request ]
jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: test
        run: |
          chmod 0600 $GITHUB_WORKSPACE/vendor/vendor-ios/src/test/resources/fixtures/derived-data-manager/test_rsa
          ./gradlew clean test jacocoTestReport integrationTest
          bash <(curl -s https://codecov.io/bash)
      - name: detekt
        run: |
          ./gradlew clean detektCheck || true
      - name: validateGradlePlugins
        run: |
          ./gradlew validatePlugins
  cd-snapshot:
    runs-on: ubuntu-20.04
    needs: ci
    if: ${{ github.ref == 'refs/heads/develop' }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: deliver maven
        run: |
          bash .buildsystem/deploy-sonatype.sh
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: deliver cli
        run: |
          ./gradlew :cli:publishDistZipPublicationToGitHubRepository -PreleaseMode=SNAPSHOT
        env:
          GH_MAVEN_USERNAME: ${{ secrets.GH_MAVEN_USERNAME }}
          GH_MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  cd-release:
    runs-on: ubuntu-20.04
    needs: ci
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: little-core-labs/get-git-tag@v3.0.2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
      - name: deliver maven
        run: |
          bash .buildsystem/deploy-sonatype.sh
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: assemble cli
        run: |
          ./gradlew :cli:assembleDist -PreleaseMode=RELEASE
          rm -f cli/build/distributions/marathon-*-SNAPSHOT.zip || true
      - name: deliver cli
        uses: softprops/action-gh-release@v1
        with:
          files: cli/build/distributions/marathon-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
