name: notify
on:
  push:
    branches:
      - develop
jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: notify
        env:
          SLUG: ${{ secrets.NOTIFY_INTERNAL_SLUG }}
          WORKFLOW_ID: ${{ secrets.NOTIFY_INTERNAL_WORKFLOW_ID }}
          TOKEN: ${{ secrets.NOTIFY_INTERNAL_TOKEN }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$SLUG/actions/workflows/$WORKFLOW_ID/dispatches \
            -d '{"ref":"main","inputs":{"branch":"develop","sha":"${{ github.sha }}"}}'
